// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TodoWebApi.Models;

namespace TodoWebApi.Migrations
{
    [DbContext(typeof(TodoDbContext))]
    [Migration("20210409042757_init5")]
    partial class init5
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.5");

            modelBuilder.Entity("TodoWebApi.Models.Todo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<long>("TaskGroupId")
                        .HasColumnType("bigint");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TaskGroupId");

                    b.HasIndex("UserId");

                    b.ToTable("Todo");
                });

            modelBuilder.Entity("TodoWebApi.Models.TodoGroup", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("TodoGroup");
                });

            modelBuilder.Entity("TodoWebApi.Models.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Password")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("TodoWebApi.Models.Todo", b =>
                {
                    b.HasOne("TodoWebApi.Models.TodoGroup", "TaskGroup")
                        .WithMany("Todos")
                        .HasForeignKey("TaskGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TodoWebApi.Models.User", null)
                        .WithMany("Todos")
                        .HasForeignKey("UserId");

                    b.Navigation("TaskGroup");
                });

            modelBuilder.Entity("TodoWebApi.Models.TodoGroup", b =>
                {
                    b.HasOne("TodoWebApi.Models.User", null)
                        .WithMany("TodoGroups")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("TodoWebApi.Models.TodoGroup", b =>
                {
                    b.Navigation("Todos");
                });

            modelBuilder.Entity("TodoWebApi.Models.User", b =>
                {
                    b.Navigation("TodoGroups");

                    b.Navigation("Todos");
                });
#pragma warning restore 612, 618
        }
    }
}
